//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHU_Synced.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Launcher : global::System.Configuration.ApplicationSettingsBase {
        
        private static Launcher defaultInstance = ((Launcher)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Launcher())));
        
        public static Launcher Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fhugame.exe")]
        public string GameExecutableName {
            get {
                return ((string)(this["GameExecutableName"]));
            }
            set {
                this["GameExecutableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FeralHeart Unleashed\\FeralHeart Unleashed.exe")]
        public string OGLauncherAbsolutePath {
            get {
                return ((string)(this["OGLauncherAbsolutePath"]));
            }
            set {
                this["OGLauncherAbsolutePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FeralHeart Unleashed")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set {
                this["GamePath"] = value;
            }
        }
    }
}
