//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHU_Synced.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Preset : global::System.Configuration.ApplicationSettingsBase {
        
        private static Preset defaultInstance = ((Preset)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Preset())));
        
        public static Preset Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FeralHeart Unleashed\\presets")]
        public string PresetsFolderLocation {
            get {
                return ((string)(this["PresetsFolderLocation"]));
            }
        }
    }
}
